export const MATEMATICAS_APLICADAS_VIDEO_URLS: Record<string, string> = {
  T01: "https://youtu.be/nAU6qF76FBU",
  T02: "https://youtu.be/YwzCxAQWV18",
  T03: "https://youtu.be/haB0a_K-atc",
  T04: "https://youtu.be/AbEuhM_mVZs",
  T05: "https://youtu.be/N9J7pRSyRnA",
  T06: "https://youtu.be/dQLYcysWWgY",
  T07: "https://youtu.be/-Qshnizjs6Y",
  T08: "https://youtu.be/NMUeZJG65gI",
  T09: "https://youtu.be/FblVieTTwKg",
  T10: "https://youtu.be/nkGZwfHAjg0",
  T11: "https://youtu.be/qR9EXFkckRA",
  T12: "https://youtu.be/16FiYFl1bhM",
  T13: "https://youtu.be/WdQTPNC483U",
  T14: "https://youtu.be/ZJ9YVBgEvss",
  T15: "https://youtu.be/Z2VAD7TpFfs",
  T16: "https://youtu.be/hDzSynaeIbQ",
  T17: "https://youtu.be/Kkb-fM8sjvM",
  T18: "https://youtu.be/DslzuhQpKeY",
  T19: "https://youtu.be/JpyUHLFxfjM",
  T20: "https://youtu.be/W-o0quWnSJ8",
  T21: "https://youtu.be/IMKzFHOqWOE",
  T22: "https://youtu.be/WXzMsufG1T8",
  T23: "https://youtu.be/c9jnXbN1zEw",
  T24: "https://youtu.be/XJRlyigYMYA",
  T25: "https://youtu.be/3htxtN57r6g",
  T26: "https://youtu.be/gj_zEWYdbso",
  T27: "https://youtu.be/YZ1gavRjx1s",
  T28: "https://youtu.be/Qj1NjBiBY9M",
  T29: "https://youtu.be/bwmMJmClrdo",
  T30: "https://youtu.be/Mxtj8N2PxD4",
  T31: "https://youtu.be/mWVbrTrF7xU",
  T32: "https://youtu.be/yzMUF8UQJnI",
  T33: "https://youtu.be/tUXgOIRYVno",
  T34: "https://youtu.be/acrewQs_4ZI",
  T35: "https://youtu.be/lrlloAgtbOw",
  T36: "https://youtu.be/qeZCue29L5U",
  T37: "https://youtu.be/rVWOl32CcNg",
  T38: "https://youtu.be/5Mjtpdsih6A",
  T39: "https://youtu.be/F4UamUAQmEA",
  T40: "https://youtu.be/SUMEr7UvQVs",
  T41: "https://youtu.be/gHwsts5j_hw",
  T42: "https://youtu.be/Rm0beJcIgOs",
  T43: "https://youtu.be/j7gI59dOrWc",
  T44: "https://youtu.be/R9cQ4k1Dff8",
};

export function toYouTubeEmbedUrl(url: string) {
  const id = url.split("/").pop();
  return id ? `https://www.youtube-nocookie.com/embed/${id}` : "";
}
