"use client";
import { useEffect, useRef, useState } from "react";
import Image from "next/image";
import { supabase } from "@/lib/supabaseClient";
type EntryPoint="rocio"|"fernando";
type Props={entryPoint:EntryPoint;courseSlug:string;contextTitle?:string;open:boolean;onClose:()=>void};
export default function CourseAssistantChat({entryPoint,courseSlug,contextTitle="",open,onClose}:Props){
 const isRocio=entryPoint==="rocio";const [message,setMessage]=useState("");const [messages,setMessages]=useState<{from:"user"|"assistant";text:string;role?:string}[]>([]);const [sending,setSending]=useState(false);const bodyRef=useRef<HTMLDivElement>(null);
 useEffect(()=>{if(open&&!messages.length)setMessages([{from:"assistant",text:isRocio?"Soy Rocío. Pregúntame lo que necesites. Si tu consulta corresponde a otro servicio de Base12, la atenderá internamente el rol adecuado sin sacarte de esta conversación.":"Soy Fernando. Puedo ayudarte con tu planificación y progreso, y también puedes preguntarme cualquier otra cuestión de Base12."}]);},[open,isRocio,messages.length]);
 useEffect(()=>{if(bodyRef.current)bodyRef.current.scrollTop=bodyRef.current.scrollHeight;},[messages]);
 if(!open)return null;
 async function send(){const text=message.trim();if(!text||sending)return;setMessage("");setSending(true);setMessages(v=>[...v,{from:"user",text}]);try{const {data}=await supabase.auth.getSession();const token=data.session?.access_token;const response=await fetch("/api/base12-assistant",{method:"POST",headers:{"Content-Type":"application/json",...(token?{Authorization:"Bearer "+token}:{})},body:JSON.stringify({entryPoint,courseSlug,contextTitle,message:text})});const payload=await response.json().catch(()=>({}));setMessages(v=>[...v,{from:"assistant",text:response.ok?(payload.answer||"No he podido responder."):"Ahora mismo no he podido resolver la consulta.",role:payload.role}]);}catch{setMessages(v=>[...v,{from:"assistant",text:"Ahora mismo no he podido resolver la consulta."}]);}finally{setSending(false);}}
 const avatar=isRocio?"/images/rocio-profesora-ia.png":"/images/fernando-tutor-ia.png";const name=isRocio?"Rocío":"Fernando";
 const roleLabel=(role?:string)=>role==="secretaria"?"Secretaría":role==="jefatura"?"Jefatura de Estudios":role==="commercial"?"Comercial":role==="direccion"?"Dirección Académica":role==="rocio"?"Rocío":role==="fernando"?"Fernando":"";
 return <div style={{position:"fixed",inset:0,zIndex:1300,background:"rgba(5,19,40,.72)",display:"grid",placeItems:"center",padding:16}} onMouseDown={onClose}><section style={{width:"min(720px,95vw)",height:"min(720px,92vh)",background:"#fff",borderRadius:18,overflow:"hidden",display:"grid",gridTemplateRows:"auto 1fr auto",boxShadow:"0 28px 70px rgba(0,0,0,.32)"}} onMouseDown={e=>e.stopPropagation()}>
 <header style={{display:"flex",alignItems:"center",justifyContent:"space-between",padding:"14px 16px",borderBottom:"1px solid #dce6ef"}}><div style={{display:"flex",alignItems:"center",gap:11}}><Image src={avatar} alt="" width={58} height={58} style={{width:50,height:50,objectFit:"cover",borderRadius:"50%"}}/><div><strong style={{display:"block",color:"#0b3c75",fontSize:18}}>{name}</strong><small style={{color:"#60758d"}}>{isRocio?"Profesora IA":"Tutor IA"} · {contextTitle||courseSlug}</small></div></div><button type="button" onClick={onClose} style={{border:"1px solid #d5e0ea",background:"#fff",borderRadius:"50%",width:36,height:36,fontSize:22,cursor:"pointer"}}>×</button></header>
 <div ref={bodyRef} style={{overflowY:"auto",padding:16,background:"#f8fbff"}}>{messages.map((m,i)=><div key={i} style={{display:"flex",justifyContent:m.from==="user"?"flex-end":"flex-start",marginBottom:10}}><div style={{maxWidth:"82%",background:m.from==="user"?"#176fd6":"#fff",color:m.from==="user"?"#fff":"#173f70",border:m.from==="user"?"none":"1px solid #dbe5ef",borderRadius:12,padding:"10px 12px",lineHeight:1.5,whiteSpace:"pre-wrap"}}>{m.from==="assistant"&&m.role&&m.role!==entryPoint?<small style={{display:"block",fontWeight:900,color:"#6b7f95",marginBottom:4}}>{roleLabel(m.role)}</small>:null}{m.text}</div></div>)}{sending?<p style={{color:"#60758d",fontSize:13}}>Preparando respuesta…</p>:null}</div>
 <div style={{display:"flex",gap:8,padding:12,borderTop:"1px solid #dce6ef",background:"#fff"}}><textarea value={message} onChange={e=>setMessage(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();void send();}}} placeholder="Escribe tu pregunta…" rows={2} style={{flex:1,resize:"none",border:"1px solid #c7d7e6",borderRadius:10,padding:"10px 11px",font:"inherit"}}/><button type="button" onClick={send} disabled={sending||!message.trim()} style={{border:0,borderRadius:10,background:"#176fd6",color:"#fff",padding:"0 16px",fontWeight:800,cursor:"pointer"}}>Enviar</button></div>
 </section></div>;
}