"use client";
/* eslint-disable @typescript-eslint/no-explicit-any, react-hooks/set-state-in-effect, react-hooks/exhaustive-deps, react-hooks/purity */
import { useEffect, useMemo, useState } from "react";
import { supabase } from "@/lib/supabaseClient";

type Question = { question:string; options:string[]; answer:number; explanation:string };
async function token(){ return (await supabase.auth.getSession()).data.session?.access_token || ""; }

export function OpenQuestion({courseSlug,themeId}:{courseSlug:string;themeId:string}){
  const [text,setText]=useState(""); const [message,setMessage]=useState(""); const [items,setItems]=useState<any[]>([]);
  const load=async()=>{const t=await token(); if(!t)return; const r=await fetch(`/api/opposition-questions?course=${courseSlug}&theme=${themeId}`,{headers:{Authorization:`Bearer ${t}`}}); if(r.ok)setItems((await r.json()).questions||[])};
  useEffect(()=>{load()},[courseSlug,themeId]);
  const send=async()=>{setMessage(""); const t=await token(); if(!t){setMessage("Inicia sesión y matricúlate para enviar preguntas abiertas.");return} const r=await fetch("/api/opposition-questions",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${t}`},body:JSON.stringify({courseSlug,themeId,question:text})}); setMessage(r.ok?"Pregunta enviada a Rocío.":"No se ha podido enviar la pregunta."); if(r.ok){setText("");load()}};
  return <section style={{marginTop:24,paddingTop:20,borderTop:"1px solid #d6e0d1"}}><h3>Hazle una pregunta abierta a Rocío</h3><textarea value={text} onChange={e=>setText(e.target.value)} maxLength={1500} placeholder="Escribe aquí tu duda sobre el tema…" style={{width:"100%",minHeight:110,padding:12,border:"1px solid #b8c9b2",borderRadius:10}}/><button onClick={send} disabled={text.trim().length<8} style={{marginTop:10,padding:"10px 16px",border:0,borderRadius:9,background:"#28643b",color:"white",fontWeight:700}}>Enviar pregunta</button>{message&&<p>{message}</p>}{items.length>0&&<div><h3>Tus preguntas</h3>{items.map(i=><article key={i.id} style={{padding:"10px 0",borderTop:"1px solid #e0e7dc"}}><b>{i.question}</b><p>{i.answer||"Pendiente de respuesta"}</p></article>)}</div>}</section>;
}

export function OppositionTest({questions,courseSlug,themeId,planSlug}:{questions:Question[];courseSlug:string;themeId:string;planSlug:string}){
  const [attempt,setAttempt]=useState(0),[position,setPosition]=useState(0),[selected,setSelected]=useState<number|null>(null),[score,setScore]=useState(0),[history,setHistory]=useState<any[]>([]);
  const size=planSlug==="esencial"?Math.min(10,questions.length):Math.min(20,questions.length);
  const sample=useMemo(()=>{const a=[...questions];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a.slice(0,size)},[questions,attempt,size]);
  const load=async()=>{const t=await token();if(!t)return;const r=await fetch(`/api/opposition-progress?course=${courseSlug}&theme=${themeId}`,{headers:{Authorization:`Bearer ${t}`}});if(r.ok)setHistory((await r.json()).attempts||[])};
  useEffect(()=>{load()},[courseSlug,themeId]); const finished=position>=sample.length,q=sample[position];
  useEffect(()=>{if(!finished||!sample.length)return; (async()=>{const t=await token();if(!t)return;await fetch("/api/course-progress",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${t}`},body:JSON.stringify({courseSlug,contentId:themeId,eventType:"assessment_submitted",progressPercent:Math.round(score/sample.length*100),metadata:{score,total:sample.length,plan:planSlug,type:planSlug==="esencial"?"theme_check":"simulation"}})});load()})()},[finished]);
  if(!sample.length)return <p>El test está en preparación.</p>;
  if(finished)return <div><h2>{planSlug==="esencial"?"Comprobación terminada":"Simulacro terminado"}</h2><p>Has acertado {score} de {sample.length} ({Math.round(score/sample.length*100)} %).</p><button onClick={()=>{setAttempt(v=>v+1);setPosition(0);setSelected(null);setScore(0)}}>Nuevo intento</button><Progress history={history}/></div>;
  return <div><p style={{fontWeight:800,color:"#28643b"}}>{planSlug==="esencial"?"COMPROBACIÓN DEL TEMA · 10 PREGUNTAS":"SIMULACRO · 20 PREGUNTAS ALEATORIAS"}</p><h2>Comprueba lo aprendido</h2><p>{position+1} / {sample.length}</p><h3>{q.question}</h3><div style={{display:"grid",gap:9}}>{q.options.map((o,i)=><button key={o} disabled={selected!==null} onClick={()=>{setSelected(i);if(i===q.answer)setScore(v=>v+1)}} style={{padding:12,textAlign:"left",border:"1px solid #b8c9b2",borderRadius:9,background:selected===null?"white":i===q.answer?"#dcfce7":i===selected?"#fee2e2":"white"}}><b>{String.fromCharCode(65+i)}.</b> {o}</button>)}</div>{selected!==null&&<div style={{marginTop:14}}><p>{q.explanation}</p><button onClick={()=>{setPosition(v=>v+1);setSelected(null)}}>{position+1===sample.length?"Ver resultado":"Siguiente pregunta"}</button></div>}<Progress history={history}/></div>;
}
function Progress({history}:{history:any[]}){if(!history.length)return <p style={{marginTop:20}}>Tu progresión aparecerá aquí después del primer intento.</p>;const best=Math.max(...history.map(x=>Number(x.progress_percent)||0));return <section style={{marginTop:24,padding:16,background:"#f3f7f0",borderRadius:12}}><h3>Tu progresión</h3><p><b>Mejor resultado: {best} %</b> · {history.length} intento{history.length===1?"":"s"}</p><div style={{display:"flex",gap:6,alignItems:"end",height:70}}>{history.slice().reverse().map((x,i)=><span key={i} title={`${x.progress_percent}%`} style={{width:18,height:`${Math.max(4,Number(x.progress_percent)||0)}%`,background:"#28643b",borderRadius:4}}/>)}</div></section>}

export function TutoringCalendar({courseSlug}:{courseSlug:string}){const[slots,setSlots]=useState<any[]>([]),[bookings,setBookings]=useState<any[]>([]),[message,setMessage]=useState("");const load=async()=>{const t=await token();const r=await fetch(`/api/tutoring?course=${courseSlug}`,{headers:{Authorization:`Bearer ${t}`}});if(r.ok){const d=await r.json();setSlots(d.slots||[]);setBookings(d.bookings||[])}};useEffect(()=>{load()},[courseSlug]);const book=async(id:string)=>{const t=await token();const r=await fetch("/api/tutoring",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${t}`},body:JSON.stringify({courseSlug,slotId:id})});const d=await r.json();setMessage(r.ok?"Tutoría reservada.":d.error==="weekly_limit"?"Ya tienes una tutoría reservada esa semana.":"Ese horario ya no está disponible.");load()};const cancel=async(id:string)=>{const t=await token();await fetch(`/api/tutoring?id=${id}`,{method:"DELETE",headers:{Authorization:`Bearer ${t}`}});setMessage("Reserva cancelada. Ya puedes elegir otro horario.");load()};return <section><h2>Tutoría humana Premium</h2><p>Reserva una sesión individual de 30 minutos cada semana. Puedes cancelar y elegir otro horario disponible.</p>{bookings.map(b=><div key={b.id} style={{padding:12,background:"#e8f3e5",borderRadius:9,marginBottom:8}}><b>Reserva activa: {new Date(b.tutoring_slots.starts_at).toLocaleString("es-ES")}</b><br/><button onClick={()=>cancel(b.id)} style={{marginTop:8}}>Cancelar o cambiar horario</button></div>)}<div style={{display:"grid",gap:8}}>{slots.map(s=><button key={s.id} onClick={()=>book(s.id)} style={{padding:12,border:"1px solid #b8c9b2",borderRadius:9,background:"white"}}>{new Date(s.starts_at).toLocaleString("es-ES",{weekday:"long",day:"numeric",month:"long",hour:"2-digit",minute:"2-digit"})}</button>)}</div>{!slots.length&&<p>No hay nuevos horarios publicados. Consulta de nuevo próximamente.</p>}{message&&<p>{message}</p>}</section>}
