export const courses = {
  "historia-espana": {
    slug: "historia-espana",
    title: "Historia de España",
    shortTitle: "Historia de España",
    price: 29,
    priceInCents: 2900,
    mode: "one_time",
    active: true,
    accessType: "lifetime",
    comingSoon: false,
  },
  "historia-filosofia": {
    slug: "historia-filosofia",
    title: "Historia de la Filosofía",
    shortTitle: "Historia de la Filosofía",
    price: null,
    priceInCents: null,
    mode: "pending",
    active: false,
    accessType: null,
    comingSoon: true,
  },
  "ofimatica-esencial": {
    slug: "ofimatica-esencial",
    courseSlug: "ofimatica",
    planSlug: "esencial",
    title: "Competencias digitales",
    shortTitle: "Competencias digitales",
    price: 49,
    priceInCents: 4900,
    mode: "one_time",
    active: true,
    accessType: "fixed_term",
    accessMonths: 6,
    comingSoon: false,
  },
  "ofimatica-estandar": {
    slug: "ofimatica-estandar",
    courseSlug: "ofimatica",
    planSlug: "estandar",
    title: "Ofimática",
    shortTitle: "Ofimática",
    price: 119,
    priceInCents: 11900,
    mode: "one_time",
    active: true,
    accessType: "fixed_term",
    accessMonths: 9,
    comingSoon: false,
  },
  "ofimatica-premium": {
    slug: "ofimatica-premium",
    courseSlug: "ofimatica",
    planSlug: "premium",
    title: "Productividad Digital e IA",
    shortTitle: "Productividad Digital e IA",
    price: 239,
    priceInCents: 23900,
    mode: "one_time",
    active: true,
    accessType: "fixed_term",
    accessMonths: 12,
    comingSoon: false,
  },
  "administrativo-ja-esencial": { slug: "administrativo-ja-esencial", courseSlug: "administrativo-ja", planSlug: "esencial", title: "Administrativo de la Junta de Andalucía · Esencial", shortTitle: "Administrativo JA · Esencial", price: 149, priceInCents: 14900, mode: "one_time", active: true, accessType: "fixed_term", accessMonths: 12, comingSoon: false },
  "administrativo-ja-estandar": { slug: "administrativo-ja-estandar", courseSlug: "administrativo-ja", planSlug: "estandar", title: "Administrativo de la Junta de Andalucía · Estándar", shortTitle: "Administrativo JA · Estándar", price: 299, priceInCents: 29900, mode: "one_time", active: true, accessType: "fixed_term", accessMonths: 12, comingSoon: false },
  "administrativo-ja-premium": { slug: "administrativo-ja-premium", courseSlug: "administrativo-ja", planSlug: "premium", title: "Administrativo de la Junta de Andalucía · Premium", shortTitle: "Administrativo JA · Premium", price: 499, priceInCents: 49900, mode: "one_time", active: true, accessType: "fixed_term", accessMonths: 12, comingSoon: false },
  "auxiliar-administrativo-ja-esencial": { slug: "auxiliar-administrativo-ja-esencial", courseSlug: "auxiliar-administrativo-ja", planSlug: "esencial", title: "Auxiliar Administrativo de la Junta de Andalucía · Esencial", shortTitle: "Auxiliar JA · Esencial", price: 149, priceInCents: 14900, mode: "one_time", active: true, accessType: "fixed_term", accessMonths: 12, comingSoon: false },
  "auxiliar-administrativo-ja-estandar": { slug: "auxiliar-administrativo-ja-estandar", courseSlug: "auxiliar-administrativo-ja", planSlug: "estandar", title: "Auxiliar Administrativo de la Junta de Andalucía · Estándar", shortTitle: "Auxiliar JA · Estándar", price: 299, priceInCents: 29900, mode: "one_time", active: true, accessType: "fixed_term", accessMonths: 12, comingSoon: false },
  "auxiliar-administrativo-ja-premium": { slug: "auxiliar-administrativo-ja-premium", courseSlug: "auxiliar-administrativo-ja", planSlug: "premium", title: "Auxiliar Administrativo de la Junta de Andalucía · Premium", shortTitle: "Auxiliar JA · Premium", price: 499, priceInCents: 49900, mode: "one_time", active: true, accessType: "fixed_term", accessMonths: 12, comingSoon: false },
  "tropa-y-marineria-esencial": { slug: "tropa-y-marineria-esencial", courseSlug: "tropa-y-marineria", planSlug: "esencial", title: "Tropa y Marinería · Esencial", shortTitle: "Tropa y Marinería · Esencial", price: 139, priceInCents: 13900, mode: "pending", active: false, accessType: "fixed_term", accessMonths: 12, comingSoon: true },
  "tropa-y-marineria-operativa": { slug: "tropa-y-marineria-operativa", courseSlug: "tropa-y-marineria", planSlug: "operativa", title: "Tropa y Marinería · Operativa", shortTitle: "Tropa y Marinería · Operativa", price: 209, priceInCents: 20900, mode: "pending", active: false, accessType: "fixed_term", accessMonths: 12, comingSoon: true },
  "tropa-y-marineria-integral": { slug: "tropa-y-marineria-integral", courseSlug: "tropa-y-marineria", planSlug: "integral", title: "Tropa y Marinería · Integral", shortTitle: "Tropa y Marinería · Integral", price: 279, priceInCents: 27900, mode: "pending", active: false, accessType: "fixed_term", accessMonths: 12, comingSoon: true },

  "clases-online-universidad-5h": {
    slug: "clases-online-universidad-5h",
    courseSlug: "clases-online",
    planSlug: "universidad-5h",
    title: "Clases Online \u00b7 Historia \u00b7 Universidad \u00b7 5 horas",
    shortTitle: "Historia Universidad \u00b7 5 h",
    price: 125,
    priceInCents: 12500,
    mode: "one_time",
    active: true,
    accessType: "class_bono",
    classService: "universidad-historia",
    classHours: 5,
    comingSoon: false,
  },
  "clases-online-universidad-10h": {
    slug: "clases-online-universidad-10h",
    courseSlug: "clases-online",
    planSlug: "universidad-10h",
    title: "Clases Online \u00b7 Historia \u00b7 Universidad \u00b7 10 horas",
    shortTitle: "Historia Universidad \u00b7 10 h",
    price: 230,
    priceInCents: 23000,
    mode: "one_time",
    active: true,
    accessType: "class_bono",
    classService: "universidad-historia",
    classHours: 10,
    comingSoon: false,
  },
  "clases-online-universidad-15h": {
    slug: "clases-online-universidad-15h",
    courseSlug: "clases-online",
    planSlug: "universidad-15h",
    title: "Clases Online \u00b7 Historia \u00b7 Universidad \u00b7 15 horas",
    shortTitle: "Historia Universidad \u00b7 15 h",
    price: 300,
    priceInCents: 30000,
    mode: "one_time",
    active: true,
    accessType: "class_bono",
    classService: "universidad-historia",
    classHours: 15,
    comingSoon: false,
  },
  "clases-online-universidad-20h": {
    slug: "clases-online-universidad-20h",
    courseSlug: "clases-online",
    planSlug: "universidad-20h",
    title: "Clases Online \u00b7 Historia \u00b7 Universidad \u00b7 20 horas",
    shortTitle: "Historia Universidad \u00b7 20 h",
    price: 400,
    priceInCents: 40000,
    mode: "one_time",
    active: true,
    accessType: "class_bono",
    classService: "universidad-historia",
    classHours: 20,
    comingSoon: false,
  },

  "clases-online-eso-bach-5h": {
    slug: "clases-online-eso-bach-5h",
    courseSlug: "clases-online",
    planSlug: "eso-bach-5h",
    title: "Clases Online \u00b7 Historia y Filosof\u00eda \u00b7 ESO y Bachillerato \u00b7 5 horas",
    shortTitle: "Historia y Filosof\u00eda \u00b7 5 h",
    price: 100,
    priceInCents: 10000,
    mode: "one_time",
    active: true,
    accessType: "class_bono",
    classService: "eso-bach-historia-filosofia",
    classHours: 5,
    comingSoon: false,
  },
  "clases-online-eso-bach-10h": {
    slug: "clases-online-eso-bach-10h",
    courseSlug: "clases-online",
    planSlug: "eso-bach-10h",
    title: "Clases Online \u00b7 Historia y Filosof\u00eda \u00b7 ESO y Bachillerato \u00b7 10 horas",
    shortTitle: "Historia y Filosof\u00eda \u00b7 10 h",
    price: 190,
    priceInCents: 19000,
    mode: "one_time",
    active: true,
    accessType: "class_bono",
    classService: "eso-bach-historia-filosofia",
    classHours: 10,
    comingSoon: false,
  },
  "clases-online-eso-bach-15h": {
    slug: "clases-online-eso-bach-15h",
    courseSlug: "clases-online",
    planSlug: "eso-bach-15h",
    title: "Clases Online \u00b7 Historia y Filosof\u00eda \u00b7 ESO y Bachillerato \u00b7 15 horas",
    shortTitle: "Historia y Filosof\u00eda \u00b7 15 h",
    price: 280,
    priceInCents: 28000,
    mode: "one_time",
    active: true,
    accessType: "class_bono",
    classService: "eso-bach-historia-filosofia",
    classHours: 15,
    comingSoon: false,
  },
  "clases-online-eso-bach-20h": {
    slug: "clases-online-eso-bach-20h",
    courseSlug: "clases-online",
    planSlug: "eso-bach-20h",
    title: "Clases Online \u00b7 Historia y Filosof\u00eda \u00b7 ESO y Bachillerato \u00b7 20 horas",
    shortTitle: "Historia y Filosof\u00eda \u00b7 20 h",
    price: 340,
    priceInCents: 34000,
    mode: "one_time",
    active: true,
    accessType: "class_bono",
    classService: "eso-bach-historia-filosofia",
    classHours: 20,
    comingSoon: false,
  },
} as const;

export type CourseSlug = keyof typeof courses;
