export type Tema = {
  slug: string;
  titulo: string;
  descripcion: string;
  contenido: string;
  estado: "bloqueado" | "en-progreso" | "completado";
  videoUrl: string;
};

export const temasHistoria: Tema[] = [
  {
    slug: "tema-1",
    titulo: "Tema 1: LA PREHISTORIA EN LA PENÍNSULA IBÉRICA",
    descripcion: "Primeros pobladores, Paleolítico, Neolítico y Edad de los Metales.",
    contenido: "Contenido del tema 1.",
    estado: "completado",
    videoUrl: "https://www.youtube.com/embed/Q4B2Cpf453k",
  },
  {
    slug: "tema-2",
    titulo: "Tema 2: PUEBLOS PRERROMANOS Y COLONIZACIONES HISTÓRICAS",
    descripcion: "Íberos, celtas, celtíberos y primeros contactos coloniales.",
    contenido: "Contenido del tema 2.",
    estado: "completado",
    videoUrl: "https://www.youtube.com/embed/wJRHxOSp4Ok",
  },
  {
    slug: "tema-3",
    titulo: "Tema 3: COLONIZACIONES MEDITERRÁNEAS",
    descripcion: "Fenicios, griegos y cartagineses en la Península Ibérica.",
    contenido: "Contenido del tema 3.",
    estado: "en-progreso",
    videoUrl: "https://www.youtube.com/embed/ZLQ0YtOYhg0",
  },
  {
    slug: "tema-4",
    titulo: "Tema 4: LA CONQUISTA ROMANA DE HISPANIA",
    descripcion: "Conquista, fases y organización del territorio hispano.",
    contenido: "Contenido del tema 4.",
    estado: "bloqueado",
    videoUrl: "https://www.youtube.com/embed/adX5lmyP33g",
  },
  {
    slug: "tema-5",
    titulo: "Tema 5: LA ROMANIZACIÓN",
    descripcion: "Integración cultural, social, jurídica y económica en Roma.",
    contenido: "Contenido del tema 5.",
    estado: "bloqueado",
    videoUrl: "https://www.youtube.com/embed/XdSNz-d34xE",
  },
  {
    slug: "tema-6",
    titulo: "Tema 6: CRISIS DEL IMPERIO Y REINO VISIGODO",
    descripcion: "Fin del Imperio romano y configuración del reino visigodo.",
    contenido: "Contenido del tema 6.",
    estado: "bloqueado",
    videoUrl: "https://www.youtube.com/embed/eK4R9Uqrzb4",
  },
  {
    slug: "tema-7",
    titulo: "Tema 7: LA CONQUISTA MUSULMANA",
    descripcion: "Invasión musulmana y primeros años de dominación.",
    contenido: "Contenido del tema 7.",
    estado: "bloqueado",
    videoUrl: "https://www.youtube.com/embed/xAsYpzvnPlM",
  },
  {
    slug: "tema-8",
    titulo: "Tema 8: EVOLUCIÓN POLÍTICA DE AL-ÁNDALUS",
    descripcion: "Emirato, califato, taifas e intervención norteafricana.",
    contenido: "Contenido del tema 8.",
    estado: "bloqueado",
    videoUrl: "https://www.youtube.com/embed/Tzo3U3KtJu0",
  },
  {
    slug: "tema-9",
    titulo: "Tema 9: SOCIEDAD Y ECONOMÍA DE AL-ÁNDALUS",
    descripcion: "Grupos sociales, agricultura, comercio y vida urbana.",
    contenido: "Contenido del tema 9.",
    estado: "bloqueado",
    videoUrl: "https://www.youtube.com/embed/W4EZQIn88_o",
  },
  {
    slug: "tema-10",
    titulo: "Tema 10: FORMACIÓN DE LOS REINOS CRISTIANOS",
    descripcion: "Orígenes y consolidación de los núcleos cristianos.",
    contenido: "Contenido del tema 10.",
    estado: "bloqueado",
    videoUrl: "https://www.youtube.com/embed/SAzwGMBT05A",
  },
  {
    slug: "tema-11",
    titulo: "Tema 11: EXPANSIÓN CRISTIANA Y REPOBLACIÓN",
    descripcion: "Avance territorial cristiano y modelos de repoblación.",
    contenido: "Contenido del tema 11.",
    estado: "bloqueado",
    videoUrl: "https://www.youtube.com/embed/j7ZV-sI3o0g",
  },
  {
    slug: "tema-12",
    titulo: "Tema 12: CRISIS DE LA BAJA EDAD MEDIA",
    descripcion: "Conflictos políticos, crisis demográfica y tensiones sociales.",
    contenido: "Contenido del tema 12.",
    estado: "bloqueado",
    videoUrl: "https://www.youtube.com/embed/ryatzFjWcDI",
  },
  {
    slug: "tema-13",
    titulo: "Tema 13: LOS REYES CATÓLICOS",
    descripcion: "Unión dinástica, política interior y expansión exterior.",
    contenido: "Contenido del tema 13.",
    estado: "bloqueado",
    videoUrl: "https://www.youtube.com/embed/4LOcyPkD0PI",
  },
  {
    slug: "tema-14",
    titulo: "Tema 14: CARLOS I (1516-1556)",
    descripcion: "Monarquía hispánica y conflictos internos y exteriores.",
    contenido: "Contenido del tema 14.",
    estado: "bloqueado",
    videoUrl: "https://www.youtube.com/embed/lwdTu3Pz0Rc",
  },
  {
    slug: "tema-15",
    titulo: "Tema 15: FELIPE II (1556-1598)",
    descripcion: "Apogeo y dificultades del imperio de Felipe II.",
    contenido: "Contenido del tema 15.",
    estado: "bloqueado",
    videoUrl: "https://www.youtube.com/embed/mvgPJcWPgCQ",
  },
  {
    slug: "tema-16",
    titulo: "Tema 16: LOS AUSTRIAS MENORES",
    descripcion: "Valimiento, gobierno y decadencia política.",
    contenido: "Contenido del tema 16.",
    estado: "bloqueado",
    videoUrl: "https://www.youtube.com/embed/2Tl86Qeo6VY",
  },
  {
    slug: "tema-17",
    titulo: "Tema 17: CRISIS DEL SIGLO XVII",
    descripcion: "Crisis económica, social y política de la monarquía hispánica.",
    contenido: "Contenido del tema 17.",
    estado: "bloqueado",
    videoUrl: "https://www.youtube.com/embed/Oy0P-8RBI7o",
  },
  {
    slug: "tema-18",
    titulo: "Tema 18: Guerra de Sucesión y Cambio Dinástico",
    descripcion: "Fin de los Austrias y llegada de los Borbones.",
    contenido: "Contenido del tema 18.",
    estado: "bloqueado",
    videoUrl: "https://www.youtube.com/embed/nlOgoDUs5_U",
  },
  {
    slug: "tema-18-bis",
    titulo: "Tema 18 bis: América en el siglo XVIII",
    descripcion: "Administración, economía y reformas en la América borbónica.",
    contenido: "Contenido del tema 18 bis.",
    estado: "bloqueado",
    videoUrl: "https://www.youtube.com/embed/N90LgNskWcw",
  },
  {
    slug: "tema-19",
    titulo: "Tema 19: Reformas Borbónicas",
    descripcion: "Centralización, administración y modernización del Estado.",
    contenido: "Contenido del tema 19.",
    estado: "bloqueado",
    videoUrl: "https://www.youtube.com/embed/qsC3QshFVVo",
  },
  {
    slug: "tema-20",
    titulo: "Tema 20: La Ilustración en España",
    descripcion: "Ideas ilustradas, reformismo y cultura del siglo XVIII.",
    contenido: "Contenido del tema 20.",
    estado: "bloqueado",
    videoUrl: "https://www.youtube.com/embed/gNWLphzTP5I",
  },
  {
    slug: "tema-21",
    titulo: "Tema 21: La Guerra de Independencia",
    descripcion: "Invasión napoleónica, resistencia y consecuencias.",
    contenido: "Contenido del tema 21.",
    estado: "bloqueado",
    videoUrl: "https://www.youtube.com/embed/B-MlID3irTI",
  },
  {
    slug: "tema-22",
    titulo: "Tema 22: Las Cortes de Cádiz y la Constitución de 1812",
    descripcion: "Nacimiento del liberalismo político español.",
    contenido: "Contenido del tema 22.",
    estado: "bloqueado",
    videoUrl: "https://www.youtube.com/embed/3id7T6-QpVg",
  },
  {
    slug: "tema-23",
    titulo: "Tema 23: Fernando VII y el absolutismo",
    descripcion: "Restauración absolutista, liberalismo y conflicto político.",
    contenido: "Contenido del tema 23.",
    estado: "bloqueado",
    videoUrl: "https://www.youtube.com/embed/dTRW3Ouplj4",
  },
  {
    slug: "tema-23-bis",
    titulo: "Tema 23 bis: La revolución industrial en España",
    descripcion: "Industrialización, transportes y cambios económicos.",
    contenido: "Contenido del tema 23 bis.",
    estado: "bloqueado",
    videoUrl: "https://www.youtube.com/embed/NEvGm-3PxNA",
  },
  {
    slug: "tema-24",
    titulo: "Tema 24: CONSTRUCCIÓN DEL ESTADO LIBERAL (1833-1868)",
    descripcion: "Reinado de Isabel II y consolidación del liberalismo.",
    contenido: "Contenido del tema 24.",
    estado: "bloqueado",
    videoUrl: "https://www.youtube.com/embed/3FHQpy4zOWM",
  },
  {
    slug: "tema-24-bis",
    titulo: "Tema 24 bis: El Sexenio Democrático (1868–1874)",
    descripcion: "Revolución, monarquía democrática, república y crisis.",
    contenido: "Contenido del tema 24 bis.",
    estado: "bloqueado",
    videoUrl: "https://www.youtube.com/embed/bBaZD3qQpk4",
  },
  {
    slug: "tema-25",
    titulo: "Tema 25: El sistema de la Restauración",
    descripcion: "Constitución de 1876, turnismo y estabilidad aparente.",
    contenido: "Contenido del tema 25.",
    estado: "bloqueado",
    videoUrl: "https://www.youtube.com/embed/Wy4QH4zu8UQ",
  },
  {
    slug: "tema-26",
    titulo: "Tema 26: Crisis de la Restauración (1902–1930)",
    descripcion: "Inestabilidad política, conflictividad social y dictadura.",
    contenido: "Contenido del tema 26.",
    estado: "bloqueado",
    videoUrl: "https://www.youtube.com/embed/GnCk7diHWqw",
  },
  {
    slug: "tema-26-bis",
    titulo: "Tema 26 bis: La guerra de Cuba (1895–1898)",
    descripcion: "Conflicto colonial y final del imperio ultramarino.",
    contenido: "Contenido del tema 26 bis.",
    estado: "bloqueado",
    videoUrl: "https://www.youtube.com/embed/D1s6Yhc_OUc",
  },
  {
    slug: "tema-26-ter",
    titulo: "Tema 26 ter: El desastre del 98 y el regeneracionismo",
    descripcion: "Crisis nacional y respuestas regeneracionistas.",
    contenido: "Contenido del tema 26 ter.",
    estado: "bloqueado",
    videoUrl: "https://www.youtube.com/embed/7JOCYiUSwPU",
  },
  {
    slug: "tema-27",
    titulo: "Tema 27: La Segunda República (1931–1936)",
    descripcion: "Reformas, conflictos y polarización política.",
    contenido: "Contenido del tema 27.",
    estado: "bloqueado",
    videoUrl: "https://www.youtube.com/embed/GNZeQOJAbWc",
  },
  {
    slug: "tema-28",
    titulo: "Tema 28: La Guerra Civil (1936–1939)",
    descripcion: "Golpe militar, desarrollo del conflicto y consecuencias.",
    contenido: "Contenido del tema 28.",
    estado: "bloqueado",
    videoUrl: "https://www.youtube.com/embed/Ci1D4rHjmkg",
  },
  {
    slug: "tema-29",
    titulo: "Tema 29: El franquismo (1939–1975)",
    descripcion: "Dictadura, autarquía, desarrollismo y oposición.",
    contenido: "Contenido del tema 29.",
    estado: "bloqueado",
    videoUrl: "https://www.youtube.com/embed/_U7hHKZz9DU",
  },
  {
    slug: "tema-30",
    titulo: "Tema 30: Transición y democracia (1975–Actualidad)",
    descripcion: "Transición, Constitución de 1978 y evolución democrática.",
    contenido: "Contenido del tema 30.",
    estado: "bloqueado",
    videoUrl: "https://www.youtube.com/embed/IdRksxYyhrs",
  },
];