export type PauProblem = {
  id: string;
  subject: "MAT2";
  block: "Álgebra" | "Geometría" | "Análisis" | "Probabilidad";
  statement: string;
  solution: string;
  rubric: string;
};

type ProblemDefinition = Omit<PauProblem, "id" | "subject">;

const DEFINITIONS: Record<string, ProblemDefinition> = {
  P01: { block: "Álgebra", statement: "Dada A = [[2,1],[1,3]], calcula det(A), decide si es invertible y obtiene A⁻¹. Verifica el resultado mediante un producto.", solution: "det(A)=2·3−1=5, distinto de cero. Por tanto A es invertible. A⁻¹=(1/5)[[3,−1],[−1,2]]. La verificación A·A⁻¹=I confirma el cálculo.", rubric: "2,5 puntos: determinante 0,6; criterio de invertibilidad 0,4; inversa 1,0; verificación/rigor 0,5." },
  P02: { block: "Geometría", statement: "Sean A(1, 2, -1) y B(4, -1, 2). Calcula el vector AB, su módulo y una ecuación paramétrica de la recta que pasa por A y B.", solution: "AB=B−A=(3, -3, 3). Su módulo es √(27)≈5.196. Una ecuación paramétrica es (x,y,z)=(1, 2, -1)+λ(3, -3, 3), es decir x=1+3λ, y=2+-3λ, z=-1+3λ.", rubric: "2,5 puntos: vector 0,7; módulo 0,6; recta 0,9; notación/comprobación 0,3." },
  P03: { block: "Análisis", statement: "Dada f(x)=x³−3x²−9x+7, estudia crecimiento y decrecimiento y clasifica sus extremos relativos.", solution: "f′(x)=3x²−6x−9=3(x−3)(x+1). Los puntos críticos son x=−1 y x=3. El signo es positivo en (−∞,−1), negativo en (−1,3) y positivo en (3,∞): máximo relativo en x=−1 y mínimo relativo en x=3. Sus ordenadas son f(−1)=12 y f(3)=-20.", rubric: "2,5 puntos: derivada 0,5; críticos 0,5; tabla de signos 0,8; extremos con coordenadas 0,7." },
  P04: { block: "Probabilidad", statement: "En un centro, el 60% del alumnado usa transporte público. Entre quienes lo usan, el 30% llega antes de las 8:00; entre quienes no lo usan, el 50% llega antes de las 8:00. Calcula la probabilidad de llegar antes de las 8:00 y, sabiendo que alguien llegó antes, la probabilidad de que use transporte público.", solution: "Por probabilidad total: P(A)=0,6·0,3+0,4·0,5=0.38. Por Bayes: P(T|A)=0,6·0,3/0.38=0.4737≈47.37%.", rubric: "2,5 puntos: árbol/partición 0,5; total 0,8; Bayes 0,8; interpretación 0,4." },
  P05: { block: "Álgebra", statement: "Resuelve por Gauss el sistema: x+y+z=4, 2x−y+z=1, x+2y+2z=7. Comprueba la solución.", solution: "La eliminación de Gauss conduce a una única solución x=1, y=2, z=1. Al sustituir en las tres ecuaciones se recuperan los términos independientes, por lo que la solución queda verificada.", rubric: "2,5 puntos: planteamiento/matriz 0,4; eliminación correcta 1,3; solución 0,4; comprobación 0,4." },
  P06: { block: "Geometría", statement: "Obtén la ecuación general del plano que pasa por P=(1, 0, 2) y tiene como vectores directores u=(1, 2, 1), v=(2, -1, 1). Comprueba que ambos directores son paralelos al plano.", solution: "Un vector normal es u×v=(3, 1, -5). Por tanto el plano es 3(x−1)+1y+-5(z−2)=0, equivalente a 3x+1y+-5z+(7)=0. Los productos n·u y n·v son cero.", rubric: "2,5 puntos: producto vectorial 0,8; ecuación 1,0; comprobación 0,5; rigor 0,2." },
  P07: { block: "Análisis", statement: "Estudia las asíntotas de f(x)=(2x²+3x−1)/(x−1) y describe el comportamiento junto a la asíntota vertical.", solution: "División: f(x)=2*x + 5+(4)/(x−1). Hay asíntota vertical x=1 porque el numerador no se anula allí y el término 4/(x−1) tiende a ±∞. La asíntota oblicua es y=2*x + 5. A la izquierda f→−∞ y a la derecha f→+∞.", rubric: "2,5 puntos: vertical 0,7; laterales 0,6; división/oblicua 0,9; explicación 0,3." },
  P08: { block: "Probabilidad", statement: "Una prueba independiente tiene probabilidad de éxito 0,3 y se repite 7 veces. Calcula la probabilidad de obtener exactamente 2 éxitos y explica por qué el modelo es binomial.", solution: "Se cumplen número fijo de ensayos, dos resultados, independencia y p constante. X~B(7,0,3). P(X=2)=C(7,2)·0,3²·0,7^5≈0.3177.", rubric: "2,5 puntos: condiciones 0,6; parámetros 0,4; fórmula 0,8; cálculo/interpretación 0,7." },
  P09: { block: "Álgebra", statement: "Estudia según el parámetro a el sistema: x+y=2; x+a·y=3. Indica para qué valor de a cambia la clasificación y resuelve los casos.", solution: "La matriz de coeficientes tiene determinante a−1. Si a≠1 hay solución única: restando ecuaciones, (a−1)y=1, de modo que y=1/(a−1) y x=2−1/(a−1). Si a=1 aparecen x+y=2 y x+y=3: contradicción; el sistema es incompatible.", rubric: "2,5 puntos: valor crítico 0,6; caso general 1,0; caso a=1 por rangos/contradicción 0,6; conclusión 0,3." },
  P10: { block: "Geometría", statement: "Calcula la distancia del punto P=(2, 1, -1) al plano 2x−y+2z−3=0. Explica por qué la fórmula representa una distancia perpendicular.", solution: "Se sustituye P en el numerador: |2·2−1+2·(−1)−3|=|−2|=2. El módulo del normal es √(4+1+4)=3. La distancia es 2/3. Se divide la proyección sobre el normal por su módulo, de ahí la perpendicularidad.", rubric: "2,5 puntos: identificación fórmula 0,5; sustitución 0,8; resultado 0,5; explicación geométrica 0,7." },
  P11: { block: "Análisis", statement: "Calcula el área encerrada entre y=x² y y=2x en el intervalo delimitado por sus puntos de corte.", solution: "Los cortes satisfacen x²=2x: x=0 y x=2. En (0,2), 2x está por encima de x². Área=∫₀²(2x−x²)dx=4/3=4/3 unidades cuadradas.", rubric: "2,5 puntos: intersecciones 0,6; orden de curvas 0,4; integral 1,0; resultado/unidades 0,5." },
  P12: { block: "Probabilidad", statement: "Una variable X sigue N(70,10²). Calcula P(60<X<80) mediante tipificación e interpreta el área.", solution: "Z=(X−70)/10. Los extremos 60 y 80 se transforman en z=−1 y z=1. P(−1<Z<1)≈0.6827. Es el área central entre una desviación típica por debajo y por encima de la media.", rubric: "2,5 puntos: tipificación 0,8; área correcta 0,6; valor 0,6; interpretación 0,5." },
  P13: { block: "Álgebra", statement: "Dada A = [[5,4],[1,6]], calcula det(A), decide si es invertible y obtiene A⁻¹. Verifica el resultado mediante un producto.", solution: "det(A)=5·6−4=26, distinto de cero. Por tanto A es invertible. A⁻¹=(1/26)[[6,−4],[−1,5]]. La verificación A·A⁻¹=I confirma el cálculo.", rubric: "2,5 puntos: determinante 0,6; criterio de invertibilidad 0,4; inversa 1,0; verificación/rigor 0,5." },
  P14: { block: "Geometría", statement: "Calcula el ángulo geométrico entre dos rectas cuyos vectores directores son u=(1, 2, -1) y v=(2, 0, 1). Indica si son perpendiculares.", solution: "u·v=1. |u|=√6 y |v|=√5. cos α=|1|/√30, por lo que α≈79.48°. Como el producto escalar no es cero, no son perpendiculares.", rubric: "2,5 puntos: producto escalar 0,5; módulos 0,5; fórmula/ángulo 1,0; conclusión 0,5." },
  P15: { block: "Análisis", statement: "Calcula ∫ x·e^x dx mediante integración por partes y comprueba el resultado derivando.", solution: "Tomamos u=x y dv=e^x dx; entonces du=dx y v=e^x. Por partes: ∫x e^x dx=x e^x−∫e^x dx=e^x(x−1)+C. Al derivar e^x(x−1) obtenemos e^x(x−1)+e^x=x e^x.", rubric: "2,5 puntos: elección u,dv 0,6; fórmula 0,5; cálculo 0,8; comprobación 0,6." },
  P16: { block: "Probabilidad", statement: "Sean A y B con P(A)=0,5, P(B)=0,4 y P(A∩B)=0,2. Calcula P(A|B) y decide si A y B son independientes.", solution: "P(A|B)=0,2/0,4=0,5. Además P(A)P(B)=0,5·0,4=0,2=P(A∩B), por lo que A y B son independientes.", rubric: "2,5 puntos: condicionada 0,9; criterio independencia 0,8; cálculo 0,5; conclusión 0,3." },
  P17: { block: "Geometría", statement: "Sean A(1, 2, -1) y B(5, -1, 2). Calcula el vector AB, su módulo y una ecuación paramétrica de la recta que pasa por A y B.", solution: "AB=B−A=(4, -3, 3). Su módulo es √(34)≈5.831. Una ecuación paramétrica es (x,y,z)=(1, 2, -1)+λ(4, -3, 3), es decir x=1+4λ, y=2+-3λ, z=-1+3λ.", rubric: "2,5 puntos: vector 0,7; módulo 0,6; recta 0,9; notación/comprobación 0,3." },
  P18: { block: "Análisis", statement: "Dada f(x)=x³−3x²−9x+8, estudia crecimiento y decrecimiento y clasifica sus extremos relativos.", solution: "f′(x)=3x²−6x−9=3(x−3)(x+1). Los puntos críticos son x=−1 y x=3. El signo es positivo en (−∞,−1), negativo en (−1,3) y positivo en (3,∞): máximo relativo en x=−1 y mínimo relativo en x=3. Sus ordenadas son f(−1)=13 y f(3)=-19.", rubric: "2,5 puntos: derivada 0,5; críticos 0,5; tabla de signos 0,8; extremos con coordenadas 0,7." },
  P19: { block: "Probabilidad", statement: "Una prueba independiente tiene probabilidad de éxito 0,3 y se repite 8 veces. Calcula la probabilidad de obtener exactamente 2 éxitos y explica por qué el modelo es binomial.", solution: "Se cumplen número fijo de ensayos, dos resultados, independencia y p constante. X~B(8,0,3). P(X=2)=C(8,2)·0,3²·0,7^6≈0.2965.", rubric: "2,5 puntos: condiciones 0,6; parámetros 0,4; fórmula 0,8; cálculo/interpretación 0,7." },
  P20: { block: "Álgebra", statement: "Dada A = [[3,3],[1,3]], calcula det(A), decide si es invertible y obtiene A⁻¹. Verifica el resultado mediante un producto.", solution: "det(A)=3·3−3=6, distinto de cero. Por tanto A es invertible. A⁻¹=(1/6)[[3,−3],[−1,3]]. La verificación A·A⁻¹=I confirma el cálculo.", rubric: "2,5 puntos: determinante 0,6; criterio de invertibilidad 0,4; inversa 1,0; verificación/rigor 0,5." },
  P21: { block: "Geometría", statement: "Sean A(1, 2, -1) y B(3, -1, 2). Calcula el vector AB, su módulo y una ecuación paramétrica de la recta que pasa por A y B.", solution: "AB=B−A=(2, -3, 3). Su módulo es √(22)≈4.690. Una ecuación paramétrica es (x,y,z)=(1, 2, -1)+λ(2, -3, 3), es decir x=1+2λ, y=2+-3λ, z=-1+3λ.", rubric: "2,5 puntos: vector 0,7; módulo 0,6; recta 0,9; notación/comprobación 0,3." },
  P22: { block: "Análisis", statement: "Dada f(x)=x³−3x²−9x+9, estudia crecimiento y decrecimiento y clasifica sus extremos relativos.", solution: "f′(x)=3x²−6x−9=3(x−3)(x+1). Los puntos críticos son x=−1 y x=3. El signo es positivo en (−∞,−1), negativo en (−1,3) y positivo en (3,∞): máximo relativo en x=−1 y mínimo relativo en x=3. Sus ordenadas son f(−1)=14 y f(3)=-18.", rubric: "2,5 puntos: derivada 0,5; críticos 0,5; tabla de signos 0,8; extremos con coordenadas 0,7." },
  P23: { block: "Álgebra", statement: "Dada A = [[6,2],[1,6]], calcula det(A), decide si es invertible y obtiene A⁻¹. Verifica el resultado mediante un producto.", solution: "det(A)=6·6−2=34, distinto de cero. Por tanto A es invertible. A⁻¹=(1/34)[[6,−2],[−1,6]]. La verificación A·A⁻¹=I confirma el cálculo.", rubric: "2,5 puntos: determinante 0,6; criterio de invertibilidad 0,4; inversa 1,0; verificación/rigor 0,5." },
  P24: { block: "Probabilidad", statement: "Una prueba independiente tiene probabilidad de éxito 0,3 y se repite 6 veces. Calcula la probabilidad de obtener exactamente 2 éxitos y explica por qué el modelo es binomial.", solution: "Se cumplen número fijo de ensayos, dos resultados, independencia y p constante. X~B(6,0,3). P(X=2)=C(6,2)·0,3²·0,7^4≈0.3241.", rubric: "2,5 puntos: condiciones 0,6; parámetros 0,4; fórmula 0,8; cálculo/interpretación 0,7." },
};

const BANK: Array<[string, string]> = [
  ["MAT2-ÁLG-01","P01"],["MAT2-GEO-01","P02"],["MAT2-ANÁ-01","P03"],["MAT2-PRO-01","P04"],
  ["MAT2-ÁLG-02","P05"],["MAT2-GEO-02","P06"],["MAT2-ANÁ-02","P07"],["MAT2-PRO-02","P08"],
  ["MAT2-ÁLG-03","P09"],["MAT2-GEO-03","P10"],["MAT2-ANÁ-03","P11"],["MAT2-PRO-03","P12"],
  ["MAT2-ÁLG-04","P13"],["MAT2-GEO-04","P14"],["MAT2-ANÁ-04","P15"],["MAT2-PRO-04","P16"],
  ["MAT2-ÁLG-05","P05"],["MAT2-GEO-05","P17"],["MAT2-ANÁ-05","P18"],["MAT2-PRO-05","P04"],
  ["MAT2-ÁLG-06","P09"],["MAT2-GEO-06","P06"],["MAT2-ANÁ-06","P07"],["MAT2-PRO-06","P19"],
  ["MAT2-ÁLG-07","P20"],["MAT2-GEO-07","P10"],["MAT2-ANÁ-07","P11"],["MAT2-PRO-07","P12"],
  ["MAT2-ÁLG-08","P05"],["MAT2-GEO-08","P14"],["MAT2-ANÁ-08","P15"],["MAT2-PRO-08","P16"],
  ["MAT2-ÁLG-09","P09"],["MAT2-GEO-09","P21"],["MAT2-ANÁ-09","P22"],["MAT2-PRO-09","P04"],
  ["MAT2-ÁLG-10","P23"],["MAT2-GEO-10","P06"],["MAT2-ANÁ-10","P07"],["MAT2-PRO-10","P24"],
  ["MAT2-ÁLG-11","P05"],["MAT2-GEO-11","P10"],["MAT2-ANÁ-11","P11"],["MAT2-PRO-11","P12"],
  ["MAT2-ÁLG-12","P09"],["MAT2-GEO-12","P14"],["MAT2-ANÁ-12","P15"],["MAT2-PRO-12","P16"],
];

export const PAU_PROBLEMS: PauProblem[] = BANK.map(([id, key]) => ({ id, subject: "MAT2", ...DEFINITIONS[key] }));

export function getPauProblems(block?: string) {
  return block ? PAU_PROBLEMS.filter((item) => item.block === block) : PAU_PROBLEMS;
}
