export type SimulationExercise = {
  label: string;
  statement: string;
  solution: string;
  rubric: string;
};

export type PauSimulation = {
  code: string;
  community: string;
  profile: string;
  exercises: SimulationExercise[];
};

type SimulationDefinition = Omit<SimulationExercise, "label">;

const D: Record<string, SimulationDefinition> = {
  S01: { statement: "Dada f(x)=x³−3x²−9x+7, estudia crecimiento y decrecimiento y clasifica sus extremos relativos.", solution: "f′(x)=3x²−6x−9=3(x−3)(x+1). Los puntos críticos son x=−1 y x=3. El signo es positivo en (−∞,−1), negativo en (−1,3) y positivo en (3,∞): máximo relativo en x=−1 y mínimo relativo en x=3. Sus ordenadas son f(−1)=12 y f(3)=-20.", rubric: "2,5 puntos: derivada 0,5; críticos 0,5; tabla de signos 0,8; extremos con coordenadas 0,7." },
  S02: { statement: "Obtén la ecuación general del plano que pasa por P=(1, 0, 2) y tiene como vectores directores u=(1, 2, 1), v=(2, -1, 1). Comprueba que ambos directores son paralelos al plano.", solution: "Un vector normal es u×v=(3, 1, -5). Por tanto el plano es 3(x−1)+1y+-5(z−2)=0, equivalente a 3x+1y+-5z+(7)=0. Los productos n·u y n·v son cero.", rubric: "2,5 puntos: producto vectorial 0,8; ecuación 1; comprobación 0,5; rigor 0,2." },
  S03: { statement: "Estudia según el parámetro a el sistema: x+y=2; x+a·y=3. Indica para qué valor de a cambia la clasificación y resuelve los casos.", solution: "La matriz de coeficientes tiene determinante a−1. Si a≠1 hay solución única: restando ecuaciones, (a−1)y=1, de modo que y=1/(a−1) y x=2−1/(a−1). Si a=1 aparecen x+y=2 y x+y=3: contradicción; el sistema es incompatible.", rubric: "2,5 puntos: valor crítico 0,6; caso general 1; caso a=1 por rangos/contradicción 0,6; conclusión 0,3." },
  S04: { statement: "Dada A = [[5,4],[1,6]], calcula det(A), decide si es invertible y obtiene A⁻¹. Verifica el resultado mediante un producto.", solution: "det(A)=5·6−4=26, distinto de cero. Por tanto A es invertible. A⁻¹=(1/26)[[6,−4],[−1,5]]. La verificación A·A⁻¹=I confirma el cálculo.", rubric: "2,5 puntos: determinante 0,6; criterio de invertibilidad 0,4; inversa 1; verificación/rigor 0,5." },
  S05: { statement: "En un centro, el 60% del alumnado usa transporte público. Entre quienes lo usan, el 30% llega antes de las 8:00; entre quienes no lo usan, el 50% llega antes de las 8:00. Calcula la probabilidad de llegar antes de las 8:00 y, sabiendo que alguien llegó antes, la probabilidad de que use transporte público.", solution: "Por probabilidad total: P(A)=0,6·0,3+0,4·0,5=0.38. Por Bayes: P(T|A)=0,6·0,3/0.38=0.4737≈47.37%.", rubric: "2,5 puntos: árbol/partición 0,5; total 0,8; Bayes 0,8; interpretación 0,4." },
  S06: { statement: "Una prueba independiente tiene probabilidad de éxito 0,3 y se repite 8 veces. Calcula la probabilidad de obtener exactamente 2 éxitos y explica por qué el modelo es binomial.", solution: "Se cumplen número fijo de ensayos, dos resultados, independencia y p constante. X~B(8,0,3). P(X=2)=C(8,2)·0,3²·0,7^6≈0.2965.", rubric: "2,5 puntos: condiciones 0,6; parámetros 0,4; fórmula 0,8; cálculo/interpretación 0,7." },
  S07: { statement: "Estudia las asíntotas de f(x)=(2x²+3x−1)/(x−1) y describe el comportamiento junto a la asíntota vertical.", solution: "División: f(x)=2*x + 5+(4)/(x−1). Hay asíntota vertical x=1 porque el numerador no se anula allí y el término 4/(x−1) tiende a ±∞. La asíntota oblicua es y=2*x + 5. A la izquierda f→−∞ y a la derecha f→+∞.", rubric: "2 puntos: vertical 0,56; laterales 0,48; división/oblicua 0,72; explicación 0,24." },
  S08: { statement: "Una variable X sigue N(70,10²). Calcula P(60<X<80) mediante tipificación e interpreta el área.", solution: "Z=(X−70)/10. Los extremos 60 y 80 se transforman en z=−1 y z=1. P(−1<Z<1)≈0.6827. Es el área central entre una desviación típica por debajo y por encima de la media.", rubric: "2 puntos: tipificación 0,64; área correcta 0,48; valor 0,48; interpretación 0,4." },
  S09: { statement: "Dada A = [[5,4],[1,6]], calcula det(A), decide si es invertible y obtiene A⁻¹. Verifica el resultado mediante un producto.", solution: "det(A)=5·6−4=26, distinto de cero. Por tanto A es invertible. A⁻¹=(1/26)[[6,−4],[−1,5]]. La verificación A·A⁻¹=I confirma el cálculo.", rubric: "2 puntos: determinante 0,48; criterio de invertibilidad 0,32; inversa 0,8; verificación/rigor 0,4." },
  S10: { statement: "Dada f(x)=x³−3x²−9x+8, estudia crecimiento y decrecimiento y clasifica sus extremos relativos.", solution: "f′(x)=3x²−6x−9=3(x−3)(x+1). Los puntos críticos son x=−1 y x=3. El signo es positivo en (−∞,−1), negativo en (−1,3) y positivo en (3,∞): máximo relativo en x=−1 y mínimo relativo en x=3. Sus ordenadas son f(−1)=13 y f(3)=-19.", rubric: "2 puntos: derivada 0,4; críticos 0,4; tabla de signos 0,64; extremos con coordenadas 0,56." },
  S11: { statement: "Calcula la distancia del punto P=(2, 1, -1) al plano 2x−y+2z−3=0. Explica por qué la fórmula representa una distancia perpendicular.", solution: "Se sustituye P en el numerador: |2·2−1+2·(−1)−3|=|−2|=2. El módulo del normal es √(4+1+4)=3. La distancia es 2/3. Se divide la proyección sobre el normal por su módulo, de ahí la perpendicularidad.", rubric: "2 puntos: identificación fórmula 0,4; sustitución 0,64; resultado 0,4; explicación geométrica 0,56." },
  S12: { statement: "Calcula el ángulo geométrico entre dos rectas cuyos vectores directores son u=(1, 2, -1) y v=(2, 0, 1). Indica si son perpendiculares.", solution: "u·v=1. |u|=√6 y |v|=√5. cos α=|1|/√30, por lo que α≈79.48°. Como el producto escalar no es cero, no son perpendiculares.", rubric: "2 puntos: producto escalar 0,4; módulos 0,4; fórmula/ángulo 0,8; conclusión 0,4." },
  S13: { statement: "Calcula el área encerrada entre y=x² y y=2x en el intervalo delimitado por sus puntos de corte.", solution: "Los cortes satisfacen x²=2x: x=0 y x=2. En (0,2), 2x está por encima de x². Área=∫₀²(2x−x²)dx=4/3=4/3 unidades cuadradas.", rubric: "2 puntos: intersecciones 0,48; orden de curvas 0,32; integral 0,8; resultado/unidades 0,4." },
  S14: { statement: "Sean A y B con P(A)=0,5, P(B)=0,4 y P(A∩B)=0,2. Calcula P(A|B) y decide si A y B son independientes.", solution: "P(A|B)=0,2/0,4=0,5. Además P(A)P(B)=0,5·0,4=0,2=P(A∩B), por lo que A y B son independientes.", rubric: "2 puntos: condicionada 0,72; criterio independencia 0,64; cálculo 0,4; conclusión 0,24." },
  S15: { statement: "Resuelve por Gauss el sistema: x+y+z=4, 2x−y+z=1, x+2y+2z=7. Comprueba la solución.", solution: "La eliminación de Gauss conduce a una única solución x=1, y=2, z=1. Al sustituir en las tres ecuaciones se recuperan los términos independientes, por lo que la solución queda verificada.", rubric: "2 puntos: planteamiento/matriz 0,32; eliminación correcta 1,04; solución 0,32; comprobación 0,32." },
  S16: { statement: "Sean A(1, 2, -1) y B(3, -1, 2). Calcula el vector AB, su módulo y una ecuación paramétrica de la recta que pasa por A y B.", solution: "AB=B−A=(2, -3, 3). Su módulo es √(22)≈4.690. Una ecuación paramétrica es (x,y,z)=(1, 2, -1)+λ(2, -3, 3), es decir x=1+2λ, y=2+-3λ, z=-1+3λ.", rubric: "2 puntos: vector 0,56; módulo 0,48; recta 0,72; notación/comprobación 0,24." },
  S17: { statement: "Calcula ∫ x·e^x dx mediante integración por partes y comprueba el resultado derivando.", solution: "Tomamos u=x y dv=e^x dx; entonces du=dx y v=e^x. Por partes: ∫x e^x dx=x e^x−∫e^x dx=e^x(x−1)+C. Al derivar e^x(x−1) obtenemos e^x(x−1)+e^x=x e^x.", rubric: "2 puntos: elección u,dv 0,48; fórmula 0,4; cálculo 0,64; comprobación 0,48." },
  S18: { statement: "Estudia según el parámetro a el sistema: x+y=2; x+a·y=3. Indica para qué valor de a cambia la clasificación y resuelve los casos.", solution: "La matriz de coeficientes tiene determinante a−1. Si a≠1 hay solución única: restando ecuaciones, (a−1)y=1, de modo que y=1/(a−1) y x=2−1/(a−1). Si a=1 aparecen x+y=2 y x+y=3: contradicción; el sistema es incompatible.", rubric: "2 puntos: valor crítico 0,48; caso general 0,8; caso a=1 por rangos/contradicción 0,48; conclusión 0,24." },
  S19: { statement: "Sean A(1, 2, -1) y B(5, -1, 2). Calcula el vector AB, su módulo y una ecuación paramétrica de la recta que pasa por A y B.", solution: "AB=B−A=(4, -3, 3). Su módulo es √(34)≈5.831. Una ecuación paramétrica es (x,y,z)=(1, 2, -1)+λ(4, -3, 3), es decir x=1+4λ, y=2+-3λ, z=-1+3λ.", rubric: "2 puntos: vector 0,56; módulo 0,48; recta 0,72; notación/comprobación 0,24." },
  S20: { statement: "Dada f(x)=x³−3x²−9x+9, estudia crecimiento y decrecimiento y clasifica sus extremos relativos.", solution: "f′(x)=3x²−6x−9=3(x−3)(x+1). Los puntos críticos son x=−1 y x=3. El signo es positivo en (−∞,−1), negativo en (−1,3) y positivo en (3,∞): máximo relativo en x=−1 y mínimo relativo en x=3. Sus ordenadas son f(−1)=14 y f(3)=-18.", rubric: "2 puntos: derivada 0,4; críticos 0,4; tabla de signos 0,64; extremos con coordenadas 0,56." },
  S21: { statement: "Una prueba independiente tiene probabilidad de éxito 0,3 y se repite 6 veces. Calcula la probabilidad de obtener exactamente 2 éxitos y explica por qué el modelo es binomial.", solution: "Se cumplen número fijo de ensayos, dos resultados, independencia y p constante. X~B(6,0,3). P(X=2)=C(6,2)·0,3²·0,7^4≈0.3241.", rubric: "2 puntos: condiciones 0,48; parámetros 0,32; fórmula 0,64; cálculo/interpretación 0,56." },
  S22: { statement: "Dada f(x)=x³−3x²−9x+9, estudia crecimiento y decrecimiento y clasifica sus extremos relativos.", solution: "f′(x)=3x²−6x−9=3(x−3)(x+1). Los puntos críticos son x=−1 y x=3. El signo es positivo en (−∞,−1), negativo en (−1,3) y positivo en (3,∞): máximo relativo en x=−1 y mínimo relativo en x=3. Sus ordenadas son f(−1)=14 y f(3)=-18.", rubric: "2,5 puntos: derivada 0,5; críticos 0,5; tabla de signos 0,8; extremos con coordenadas 0,7." },
  S23: { statement: "Dada A = [[6,2],[1,6]], calcula det(A), decide si es invertible y obtiene A⁻¹. Verifica el resultado mediante un producto.", solution: "det(A)=6·6−2=34, distinto de cero. Por tanto A es invertible. A⁻¹=(1/34)[[6,−2],[−1,6]]. La verificación A·A⁻¹=I confirma el cálculo.", rubric: "2,5 puntos: determinante 0,6; criterio de invertibilidad 0,4; inversa 1; verificación/rigor 0,5." },
  S24: { statement: "Una variable X sigue N(70,10²). Calcula P(60<X<80) mediante tipificación e interpreta el área.", solution: "Z=(X−70)/10. Los extremos 60 y 80 se transforman en z=−1 y z=1. P(−1<Z<1)≈0.6827. Es el área central entre una desviación típica por debajo y por encima de la media.", rubric: "1,5 puntos: tipificación 0,48; área correcta 0,36; valor 0,36; interpretación 0,3." },
  S25: { statement: "Calcula el ángulo geométrico entre dos rectas cuyos vectores directores son u=(1, 2, -1) y v=(2, 0, 1). Indica si son perpendiculares.", solution: "u·v=1. |u|=√6 y |v|=√5. cos α=|1|/√30, por lo que α≈79.48°. Como el producto escalar no es cero, no son perpendiculares.", rubric: "1 puntos: producto escalar 0,2; módulos 0,2; fórmula/ángulo 0,4; conclusión 0,2." },
  S26: { statement: "Dada A = [[3,3],[1,3]], calcula det(A), decide si es invertible y obtiene A⁻¹. Verifica el resultado mediante un producto.", solution: "det(A)=3·3−3=6, distinto de cero. Por tanto A es invertible. A⁻¹=(1/6)[[3,−3],[−1,3]]. La verificación A·A⁻¹=I confirma el cálculo.", rubric: "2 puntos: determinante 0,48; criterio de invertibilidad 0,32; inversa 0,8; verificación/rigor 0,4." },
  S27: { statement: "Dada f(x)=x³−3x²−9x+7, estudia crecimiento y decrecimiento y clasifica sus extremos relativos.", solution: "f′(x)=3x²−6x−9=3(x−3)(x+1). Los puntos críticos son x=−1 y x=3. El signo es positivo en (−∞,−1), negativo en (−1,3) y positivo en (3,∞): máximo relativo en x=−1 y mínimo relativo en x=3. Sus ordenadas son f(−1)=12 y f(3)=-20.", rubric: "2 puntos: derivada 0,4; críticos 0,4; tabla de signos 0,64; extremos con coordenadas 0,56." },
  S28: { statement: "En un centro, el 60% del alumnado usa transporte público. Entre quienes lo usan, el 30% llega antes de las 8:00; entre quienes no lo usan, el 50% llega antes de las 8:00. Calcula la probabilidad de llegar antes de las 8:00 y, sabiendo que alguien llegó antes, la probabilidad de que use transporte público.", solution: "Por probabilidad total: P(A)=0,6·0,3+0,4·0,5=0.38. Por Bayes: P(T|A)=0,6·0,3/0.38=0.4737≈47.37%.", rubric: "2 puntos: árbol/partición 0,4; total 0,64; Bayes 0,64; interpretación 0,32." },
  S29: { statement: "Dada A = [[6,2],[1,6]], calcula det(A), decide si es invertible y obtiene A⁻¹. Verifica el resultado mediante un producto.", solution: "det(A)=6·6−2=34, distinto de cero. Por tanto A es invertible. A⁻¹=(1/34)[[6,−2],[−1,6]]. La verificación A·A⁻¹=I confirma el cálculo.", rubric: "2 puntos: determinante 0,48; criterio de invertibilidad 0,32; inversa 0,8; verificación/rigor 0,4." },
  S30: { statement: "Sean A(1, 2, -1) y B(4, -1, 2). Calcula el vector AB, su módulo y una ecuación paramétrica de la recta que pasa por A y B.", solution: "AB=B−A=(3, -3, 3). Su módulo es √(27)≈5.196. Una ecuación paramétrica es (x,y,z)=(1, 2, -1)+λ(3, -3, 3), es decir x=1+3λ, y=2+-3λ, z=-1+3λ.", rubric: "2 puntos: vector 0,56; módulo 0,48; recta 0,72; notación/comprobación 0,24." },
  S31: { statement: "Obtén la ecuación general del plano que pasa por P=(1, 0, 2) y tiene como vectores directores u=(1, 2, 1), v=(2, -1, 1). Comprueba que ambos directores son paralelos al plano.", solution: "Un vector normal es u×v=(3, 1, -5). Por tanto el plano es 3(x−1)+1y+-5(z−2)=0, equivalente a 3x+1y+-5z+(7)=0. Los productos n·u y n·v son cero.", rubric: "2 puntos: producto vectorial 0,64; ecuación 0,8; comprobación 0,4; rigor 0,16." },
  S32: { statement: "Dada A = [[2,1],[1,3]], calcula det(A), decide si es invertible y obtiene A⁻¹. Verifica el resultado mediante un producto.", solution: "det(A)=2·3−1=5, distinto de cero. Por tanto A es invertible. A⁻¹=(1/5)[[3,−1],[−1,2]]. La verificación A·A⁻¹=I confirma el cálculo.", rubric: "2 puntos: determinante 0,48; criterio de invertibilidad 0,32; inversa 0,8; verificación/rigor 0,4." },
  S33: { statement: "Una prueba independiente tiene probabilidad de éxito 0,3 y se repite 8 veces. Calcula la probabilidad de obtener exactamente 2 éxitos y explica por qué el modelo es binomial.", solution: "Se cumplen número fijo de ensayos, dos resultados, independencia y p constante. X~B(8,0,3). P(X=2)=C(8,2)·0,3²·0,7^6≈0.2965.", rubric: "2 puntos: condiciones 0,48; parámetros 0,32; fórmula 0,64; cálculo/interpretación 0,56." },
};

type SimulationMap = { code: string; community: string; profile: string; exercises: Array<[string, string]> };

const MAPS: SimulationMap[] = [
  { code: "AND", community: "Andalucía", profile: "Perfil 2026 verificado; actualizar 2027 · 90 minutos · 10 puntos", exercises: [["Obligatorio 1 · 2.5 puntos","S01"],["Obligatorio 2 · 2.5 puntos","S02"],["Bloque A1 · 2.5 puntos · elige A1 o A2","S03"],["Bloque A2 · 2.5 puntos · elige A1 o A2","S04"],["Bloque B1 · 2.5 puntos · elige B1 o B2","S05"],["Bloque B2 · 2.5 puntos · elige B1 o B2","S06"]] },
  { code: "ARA", community: "Aragón", profile: "Perfil 2026 oficial verificado · 90 minutos · 10 puntos", exercises: [["P1 · 2 puntos","S07"],["P2 · 2 puntos","S08"],["P3 · 2 puntos","S09"],["P4A · 2 puntos · elige P4A o P4B","S10"],["P4B · 2 puntos · elige P4A o P4B","S07"],["P5A · 2 puntos · elige P5A o P5B","S11"],["P5B · 2 puntos · elige P5A o P5B","S12"]] },
  { code: "AST", community: "Principado de Asturias", profile: "Perfil 2026 perfil armonizado provisional · 90 minutos · 10 puntos", exercises: [["P1 · 2 puntos","S13"],["P2 · 2 puntos","S14"],["P3 · 2 puntos","S15"],["P4A · 2 puntos · elige A/B","S07"],["P4B · 2 puntos · elige A/B","S13"],["P5A · 2 puntos · elige A/B","S12"],["P5B · 2 puntos · elige A/B","S16"]] },
  { code: "BAL", community: "Illes Balears", profile: "Perfil 2026 oficial verificado · 90 minutos · 10 puntos", exercises: [["A1 · 2 puntos","S12"],["A2 · 2 puntos","S17"],["A3 · 2 puntos","S14"],["B1A · 2 puntos · elige A/B","S07"],["B1B · 2 puntos · elige A/B","S13"],["B2A · 2 puntos · elige A/B","S15"],["B2B · 2 puntos · elige A/B","S18"]] },
  { code: "CAN", community: "Canarias", profile: "Perfil 2026 oficial verificado · 90 minutos · 10 puntos", exercises: [["I-1 · 2 puntos","S10"],["I-2 · 2 puntos","S15"],["I-3 · 2 puntos","S19"],["II-A1 · 2 puntos · elige una de Análisis","S17"],["II-A2 · 2 puntos · elige una de Análisis","S20"],["II-P1 · 2 puntos · elige una de Probabilidad","S21"],["II-P2 · 2 puntos · elige una de Probabilidad","S08"]] },
  { code: "CAT", community: "Cataluña", profile: "Perfil 2026 oficial verificado · 90 minutos · 10 puntos", exercises: [["E1 · 2.5 puntos","S22"],["E2 · 2.5 puntos","S23"],["E3a · 1.5 puntos","S24"],["E3b · 1 puntos","S25"],["E4A · 2.5 puntos · elige E4A o E4B","S01"],["E4B · 2.5 puntos · elige E4A o E4B","S02"]] },
  { code: "CLM", community: "Castilla-La Mancha", profile: "Perfil 2026 oficial verificado · 90 minutos · 10 puntos", exercises: [["P1 · 2 puntos","S13"],["P2 · 2 puntos","S08"],["P3 · 2 puntos","S26"],["P4A · 2 puntos · elige una","S20"],["P4B · 2 puntos · elige una","S07"],["P5A · 2 puntos · elige una","S11"],["P5B · 2 puntos · elige una","S12"]] },
  { code: "CNT", community: "Cantabria", profile: "Perfil 2026 estructura base 2025/26; revisar 2027 · 90 minutos · 10 puntos", exercises: [["P1 · 2 puntos","S07"],["P2 · 2 puntos","S08"],["P3 · 2 puntos","S15"],["P4A · 2 puntos · elige A/B","S20"],["P4B · 2 puntos · elige A/B","S07"],["P5A · 2 puntos · elige A/B","S11"],["P5B · 2 puntos · elige A/B","S12"]] },
  { code: "CVA", community: "Comunitat Valenciana", profile: "Perfil 2026 perfil oficial; estructura fina provisional · 90 minutos · 10 puntos", exercises: [["P1 · 2 puntos","S07"],["P2 · 2 puntos","S08"],["P3 · 2 puntos","S18"],["P4A · 2 puntos · elige A/B","S27"],["P4B · 2 puntos · elige A/B","S07"],["P5A · 2 puntos · elige A/B","S11"],["P5B · 2 puntos · elige A/B","S12"]] },
  { code: "CYL", community: "Castilla y León", profile: "Perfil 2026 perfil oficial disponible; estructura fina provisional · 90 minutos · 10 puntos", exercises: [["P1 · 2 puntos","S17"],["P2 · 2 puntos","S28"],["P3 · 2 puntos","S29"],["P4A · 2 puntos · elige A/B","S13"],["P4B · 2 puntos · elige A/B","S17"],["P5A · 2 puntos · elige A/B","S30"],["P5B · 2 puntos · elige A/B","S31"]] },
  { code: "EXT", community: "Extremadura", profile: "Perfil TRANSICIÓN: 2026-27 exige nueva comprobación · 90 minutos · 10 puntos", exercises: [["P1 · 2 puntos","S13"],["P2 · 2 puntos","S14"],["P3 · 2 puntos","S32"],["P4A · 2 puntos · elige A/B","S07"],["P4B · 2 puntos · elige A/B","S13"],["P5A · 2 puntos · elige A/B","S12"],["P5B · 2 puntos · elige A/B","S19"]] },
  { code: "GAL", community: "Galicia", profile: "Perfil 2026 oficial verificado parcialmente · 90 minutos · 10 puntos", exercises: [["P1 · 2 puntos","S17"],["P2 · 2 puntos","S28"],["P3 · 2 puntos","S15"],["P4A · 2 puntos · elige A/B","S13"],["P4B · 2 puntos · elige A/B","S17"],["P5A · 2 puntos · elige A/B","S19"],["P5B · 2 puntos · elige A/B","S31"]] },
  { code: "MAD", community: "Comunidad de Madrid", profile: "Perfil 2026 oficial verificado MAT2; MACS según modelo 2026 · 90 minutos · 10 puntos", exercises: [["P1 · 2 puntos","S27"],["P2 · 2 puntos","S15"],["P3 · 2 puntos","S08"],["P4A · 2 puntos · elige una","S17"],["P4B · 2 puntos · elige una","S10"],["P5A · 2 puntos · elige una","S31"],["P5B · 2 puntos · elige una","S11"]] },
  { code: "MUR", community: "Región de Murcia", profile: "Perfil 2026 estructura pendiente de fuente oficial directa · 90 minutos · 10 puntos", exercises: [["P1 · 2 puntos","S07"],["P2 · 2 puntos","S08"],["P3 · 2 puntos","S09"],["P4A · 2 puntos · elige A/B","S10"],["P4B · 2 puntos · elige A/B","S07"],["P5A · 2 puntos · elige A/B","S11"],["P5B · 2 puntos · elige A/B","S12"]] },
  { code: "NAV", community: "Navarra", profile: "Perfil 2026 perfil armonizado provisional · 90 minutos · 10 puntos", exercises: [["P1 · 2 puntos","S13"],["P2 · 2 puntos","S14"],["P3 · 2 puntos","S15"],["P4A · 2 puntos · elige A/B","S07"],["P4B · 2 puntos · elige A/B","S13"],["P5A · 2 puntos · elige A/B","S12"],["P5B · 2 puntos · elige A/B","S16"]] },
  { code: "PVA", community: "País Vasco", profile: "Perfil 2026 examen oficial disponible · 90 minutos · 10 puntos", exercises: [["P1 · 2 puntos","S17"],["P2 · 2 puntos","S28"],["P3 · 2 puntos","S18"],["P4A · 2 puntos · elige A/B","S13"],["P4B · 2 puntos · elige A/B","S17"],["P5A · 2 puntos · elige A/B","S16"],["P5B · 2 puntos · elige A/B","S31"]] },
  { code: "RIO", community: "La Rioja", profile: "Perfil 2026 oficial: misma estructura que 2025; detalle por materia revisable · 90 minutos · 10 puntos", exercises: [["P1 · 2 puntos","S10"],["P2 · 2 puntos","S33"],["P3 · 2 puntos","S26"],["P4A · 2 puntos · elige A/B","S17"],["P4B · 2 puntos · elige A/B","S20"],["P5A · 2 puntos · elige A/B","S31"],["P5B · 2 puntos · elige A/B","S11"]] },
];

export const MAT2_SIMULATIONS: PauSimulation[] = MAPS.map((simulation) => ({
  code: simulation.code,
  community: simulation.community,
  profile: simulation.profile,
  exercises: simulation.exercises.map(([label, key]) => ({ label, ...D[key] })),
}));

export function getPauSimulation(code: string) {
  return MAT2_SIMULATIONS.find((item) => item.code === code) ?? null;
}
