export const MATEMATICAS_II_VIDEO_URLS: Record<string, string> = {
  T01: "https://youtu.be/KSKFo32h8nI",
  T02: "https://youtu.be/1m_eFNJzNjc",
  T03: "https://youtu.be/8-Qml7Kpg5c",
  T04: "https://youtu.be/TsA292DOi5o",
  T05: "https://youtu.be/iH7wbWpGeJA",
  T06: "https://youtu.be/b-TVe3CXkP4",
  T07: "https://youtu.be/zw1nbq5gIp0",
  T08: "https://youtu.be/RMQhkK3K-yw",
  T09: "https://youtu.be/xfRIstA1tQI",
  T10: "https://youtu.be/wuSrYDPlJh8",
  T11: "https://youtu.be/DfJzFT2THLI",
  T12: "https://youtu.be/mYY4z6yZXzU",
  T13: "https://youtu.be/6MLKTWNN9gA",
  T14: "https://youtu.be/C2gI9PMZFSI",
  T15: "https://youtu.be/uGfkqYi0sOs",
  T16: "https://youtu.be/pntUqWxu9Bk",
  T17: "https://youtu.be/9M0Qha99_70",
  T18: "https://youtu.be/RO9GRyy7fa8",
  T19: "https://youtu.be/fgRE0FvNN_U",
  T20: "https://youtu.be/EMm_nROCAs0",
  T21: "https://youtu.be/9g4grsmP4qY",
  T22: "https://youtu.be/Vq6My544ucg",
  T23: "https://youtu.be/_rojen66pu8",
  T24: "https://youtu.be/uhbK2RWaqyQ",
  T25: "https://youtu.be/-5WAz7vISXs",
  T26: "https://youtu.be/GE8jkubgxb0",
  T27: "https://youtu.be/qtTNBNHXv7E",
  T28: "https://youtu.be/u_YO7QV3B84",
  T29: "https://youtu.be/noKQQLTXp3c",
  T30: "https://youtu.be/dyfgzpjOJqE",
  T31: "https://youtu.be/dJaAJ0e41Es",
  T32: "https://youtu.be/1W19eeUWb4E",
  T33: "https://youtu.be/c23Lddz75A8",
  T34: "https://youtu.be/FOJ-XNZKDZQ",
  T35: "https://youtu.be/wJbr8KBGMi4",
  T36: "https://youtu.be/_5XHQkE53S4",
  T37: "https://youtu.be/7VehMKE10cs",
  T38: "https://youtu.be/gA_VG_KvoPY",
  T39: "https://youtu.be/FW6Q3EnCDkM",
  T40: "https://youtu.be/ysMYwiy0WoI",
  T41: "https://youtu.be/QmSmUQwz9zg",
  T42: "https://youtu.be/eJLqlCHe-wU",
  T43: "https://youtu.be/aq-bZXq2F40",
  T44: "https://youtu.be/C8TAAlD7OGA",
  T45: "https://youtu.be/iksqADrxMPw",
  "MAT2-PROB-01": "https://youtu.be/wBPLTFFlu4k",
  "MAT2-PROB-02": "https://youtu.be/MhFah_k6d44",
  "MAT2-PROB-03": "https://youtu.be/PYsa_1iRrHw",
  "MAT2-PROB-04": "https://youtu.be/1JgvwJjJcrk",
};

export function toYouTubeEmbedUrl(url: string) {
  const id = url.split("/").pop();
  return id ? `https://www.youtube-nocookie.com/embed/${id}` : "";
}
