"use client";
import { useEffect,useState } from "react";
import { supabase } from "@/lib/supabaseClient";

type Question={id:string;question:string};
type Result={id:string;correct:boolean;matchedKeywords:string[];totalKeywords:number;keywords:string[];answerGuide:string};

export default function ShortsPage(){
  const [tema,setTema]=useState("tema-1"),[questions,setQuestions]=useState<Question[]>([]),[answers,setAnswers]=useState<Record<string,string>>({});
  const [results,setResults]=useState<Record<string,Result>>({}),[score,setScore]=useState<number|null>(null),[showResults,setShowResults]=useState(false),[showSuccess,setShowSuccess]=useState(false),[nextTheme,setNextTheme]=useState<string|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState("");
  useEffect(()=>{const p=new URLSearchParams(window.location.search);setTema(p.get("tema")||"tema-1")},[]);
  async function headers(){const {data}=await supabase.auth.getSession();return data.session?.access_token?{Authorization:"Bearer "+data.session.access_token}:{};}
  async function load(){setLoading(true);setError("");setAnswers({});setResults({});setScore(null);setShowResults(false);setShowSuccess(false);const h=await headers();const r=await fetch("/api/history-legacy-shorts?tema="+encodeURIComponent(tema),{headers:h});const d=await r.json().catch(()=>({}));if(r.ok)setQuestions(d.questions||[]);else{setQuestions([]);setError(d.error==="authentication_required"?"Debes iniciar sesión.":d.error==="matriculation_required"?"Necesitas una matrícula activa de Historia de España.":"No se han podido cargar las preguntas.");}setLoading(false)}
  useEffect(()=>{void load()},[tema]);
  async function submit(){const h=await headers();if(!("Authorization" in h)){setError("Debes iniciar sesión.");return;}const r=await fetch("/api/history-legacy-shorts",{method:"POST",headers:{"Content-Type":"application/json",...h},body:JSON.stringify({tema,answers,questionIds:questions.map(q=>q.id)})});const d=await r.json().catch(()=>({}));if(!r.ok){setError("No se han podido corregir las respuestas.");return;}const map:Record<string,Result>={};for(const item of d.results||[])map[item.id]=item;setResults(map);setScore(d.score);setShowResults(true);setShowSuccess(Boolean(d.unlocked));setNextTheme(d.nextTheme||null)}
  return <div style={{padding:32,maxWidth:900,margin:"0 auto"}}><h1>Preguntas cortas {tema}</h1>{error?<p style={{color:"#b42318"}}>{error}</p>:null}{loading?<p>Cargando preguntas…</p>:questions.length===0?<p>No hay preguntas para este tema.</p>:<>
    {questions.map((q,index)=>{const result=results[q.id];return <div key={q.id} style={{marginBottom:20,padding:16,border:"1px solid #ddd",borderRadius:12,background:showResults?(result?.correct?"#f0fdf4":"#fef2f2"):"white"}}><p style={{fontWeight:"bold"}}>{index+1}. {q.question}</p><textarea value={answers[q.id]||""} disabled={showResults} onChange={e=>setAnswers(v=>({...v,[q.id]:e.target.value}))} placeholder="Escribe tu respuesta" style={{width:"100%",minHeight:120,padding:12,borderRadius:10,border:"1px solid #d1d5db",fontSize:15,marginTop:10}}/>{showResults&&result?<div style={{marginTop:12}}><p><strong>Resultado:</strong> {result.correct?"Correcta":"Incorrecta"}</p><p><strong>Claves necesarias:</strong> {result.keywords.join(", ")}</p><p><strong>Coincidencias encontradas:</strong> {result.matchedKeywords.length?result.matchedKeywords.join(", "):"Ninguna"}</p>{!result.correct?<p><strong>Respuesta guía:</strong> {result.answerGuide}</p>:null}</div>:null}</div>})}
    {!showResults?<button onClick={()=>void submit()} disabled={questions.some(q=>!(answers[q.id]||"").trim())}>Corregir</button>:<><h2 style={{marginTop:24}}>Resultado: {score}%</h2>{showSuccess?<div style={{marginTop:16,padding:16,background:"#dcfce7",border:"1px solid #16a34a",borderRadius:12,textAlign:"center",fontWeight:"bold"}}>Has desbloqueado el siguiente tema</div>:null}{showSuccess&&nextTheme?<p><a href={"/dashboard/tema/"+nextTheme}>Ir al siguiente tema</a></p>:null}<button onClick={()=>void load()}>Repetir</button></>}
  </>}</div>;
}
