-- Tehalo fue desacoplado de la base de datos de Base12 Academy.
-- Las solicitudes privadas de Editorial EC Libros / Tehalo se almacenan en
-- el proyecto Supabase independiente de EC Libros.
--
-- Esta migración queda intencionadamente como no-op para evitar crear
-- tehalo_opposition_requests dentro del proyecto académico de Base12.
