create table if not exists public.contract_acceptances (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  order_id text not null unique,
  catalog_slug text not null,
  legal_version text not null,
  terms_accepted boolean not null,
  privacy_acknowledged boolean not null,
  immediate_access_requested boolean not null default false,
  withdrawal_acknowledged boolean not null default false,
  marketing_consent boolean not null default false,
  contract_snapshot jsonb not null,
  ip_hash text,
  user_agent text,
  accepted_at timestamptz not null default now(),
  payment_confirmed_at timestamptz,
  confirmation_sent_at timestamptz,
  created_at timestamptz not null default now()
);

alter table public.contract_acceptances enable row level security;
drop policy if exists "Users can read their contract acceptances" on public.contract_acceptances;
create policy "Users can read their contract acceptances"
on public.contract_acceptances for select to authenticated
using (auth.uid() = user_id);
revoke all on table public.contract_acceptances from anon;
grant select on table public.contract_acceptances to authenticated;
grant all on table public.contract_acceptances to service_role;

alter table public.course_enrollments
  add column if not exists consent_id uuid references public.contract_acceptances(id),
  add column if not exists first_content_accessed_at timestamptz;

create table if not exists public.course_learning_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  enrollment_id uuid not null references public.course_enrollments(id) on delete cascade,
  course_slug text not null,
  content_id text not null,
  event_type text not null check (
    event_type in ('opened', 'video_started', 'video_completed', 'activity_started',
      'activity_completed', 'content_completed', 'assessment_submitted')
  ),
  progress_percent numeric(5,2) check (
    progress_percent is null or (progress_percent >= 0 and progress_percent <= 100)
  ),
  metadata jsonb not null default '{}'::jsonb,
  occurred_at timestamptz not null default now()
);

create index if not exists course_learning_events_user_course_idx
  on public.course_learning_events (user_id, course_slug, occurred_at desc);
create index if not exists course_learning_events_enrollment_idx
  on public.course_learning_events (enrollment_id, occurred_at desc);

alter table public.course_learning_events enable row level security;
drop policy if exists "Users can read their learning events" on public.course_learning_events;
create policy "Users can read their learning events"
on public.course_learning_events for select to authenticated
using (auth.uid() = user_id);
revoke all on table public.course_learning_events from anon;
grant select on table public.course_learning_events to authenticated;
grant all on table public.course_learning_events to service_role;

create table if not exists public.personal_access_codes (
  id uuid primary key default gen_random_uuid(),
  code_hash text not null unique,
  code_hint text not null,
  assigned_email text not null,
  course_slug text not null,
  plan_slug text not null,
  access_months integer check (access_months is null or access_months > 0),
  expires_at timestamptz not null,
  redeemed_by uuid references auth.users(id) on delete set null,
  redeemed_at timestamptz,
  created_by uuid not null references auth.users(id) on delete restrict,
  note text,
  created_at timestamptz not null default now()
);

create index if not exists personal_access_codes_email_idx
  on public.personal_access_codes (lower(assigned_email));
alter table public.personal_access_codes enable row level security;
revoke all on table public.personal_access_codes from anon, authenticated;
grant all on table public.personal_access_codes to service_role;

